### ISSUE TITLE
Shutterstock corpus link is unavailable

### ISSUE THREAD

**Issue by TranHuyen1191** [ukyh/RemovingSpuriousAlignment#1]
Hi Ukyo. 

I could not access to Shutterstock corpus link (https://rochester.box.com/s/f7g31ufkp19vd6l3y9jpzf7gnjcxqxpd)
The link is unavailable.

Can you resolve this issue? Thank you in advance.

**Comment by ukyh** [comment]
Hi, thank you for letting me know this.
The link was provided by [unsupervised_captioning](https://github.com/fengyang0317/unsupervised_captioning) and seems to have expired recently.
I updated the link to [unsupervised_captioning](https://github.com/fengyang0317/unsupervised_captioning), so please follow the download instruction on that page.

**Comment by TranHuyen1191** [comment]
> Hi, thank you for letting me know this. The link was provided by [unsupervised_captioning](https://github.com/fengyang0317/unsupervised_captioning) and seems to have expired recently. I updated the link to [unsupervised_captioning](https://github.com/fengyang0317/unsupervised_captioning), so please follow the download instruction on that page.

Thank you.
